### ISSUE TITLE
What exactly is the Silicon_API_key we should be using?

### ISSUE THREAD

**Issue by JessicaHu03** [InternLM/MindSearch#207]
### Discussed in https://github.com/InternLM/MindSearch/discussions/206

<div type='discussions-op-text'>

<sup>Originally posted by **JessicaHu03** September 17, 2024</sup>
In the .env file, there are these two configs requried.

SILICON_API_KEY=
SILICON_MODEL=

Can you please provide me the link of the silicon you refer to in this case so I can go get the configs needed? Thanks</div>

**Comment by JessicaHu03** [comment]
Hello? You did not even bothered to answer my question before closing it up????

**Comment by Harold-lkk** [comment]
Hi, sorry for the inconvenience! The reason your issue was closed without a response is that we recently pushed a major update, and as part of the process, we closed all open issues. We are working hard to improve the project, and I appreciate your understanding. Please feel free to reopen this issue or create a new one if you still need assistance!

Thanks for your patience and support!


Silicon Official web is https://siliconflow.cn/zh-cn/
