### ISSUE TITLE
UnboundLocalError: local variable 'code' referenced before assignment

### ISSUE THREAD

**Issue by Yue-Rain** [InternLM/MindSearch#40]
https://github.com/InternLM/MindSearch/blob/883c66c7340a9196e29a1e166a39f86bb8a17af2/mindsearch/agent/mindsearch_agent.py#L233

![image](https://github.com/user-attachments/assets/82d600ce-2c5f-4ae6-b19c-eded467a7a17)

**Comment by liujiangning30** [comment]
Maybe you can try the model `internlm/internlm2_5-7b-chat`

**Comment by thisisvk45** [comment]
The error `UnboundLocalError: local variable 'code' referenced before assignment` occurs because the variable `code` is used before being assigned a value. To fix this, ensure `code` is initialized before it's referenced.

**Steps to Fix:**

1. **Locate the Error:**
   - Open `mindsearch_agent.py` at line 233.

2. **Initialize `code` Before Use:**
   - Ensure `code` is defined before any condition checks.

**Example Fix:**

```python
def stream_chat(message):
    code = None  # Initialize 'code' to avoid reference before assignment
    # Your existing logic to assign 'code'
    if some_condition:
        code = "some value"

    if code:
        # Logic when 'code' has a value
```

Ensure `code` is assigned a value based on your logic flow before the `if code:` check.
